name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Install backend dependencies
        run: yarn install --frozen-lockfile
        working-directory: apps/api

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: apps/web

      - name: Start backend and frontend servers
        run: |
          yarn --cwd apps/api dev &
          yarn --cwd apps/web dev &
          npx wait-on http://localhost:3333 http://localhost:8080
        shell: bash

      - name: Run Playwright tests
        run: npx playwright test
