name: E2E Tests via Playwright

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: yarn install

      - name: Install wait-on
        run: yarn add --dev wait-on

      - name: Start backend (porta 3333)
        run: |
          cd apps/api
          yarn install
          yarn dev &
        working-directory: .

      - name: Start frontend (porta 8080)
        run: |
          cd apps/web
          yarn install
          yarn dev &
        working-directory: .

      - name: Wait for services
        run: yarn wait-on http://localhost:3333 http://localhost:8080

      - name: Run Playwright tests
        run: npx playwright test --exit-on-failure

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
