name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Start backend and frontend servers
        run: |
          # Inicia backend em background
          yarn --cwd apps/api dev &

          # Inicia frontend em background
          yarn --cwd apps/web dev &

          # Aguarda os servidores estarem disponíveis
          npx wait-on http://localhost:3333 http://localhost:8080
        # Permite o uso de & para rodar em background
        shell: bash

      - name: Run Playwright tests
        run: npx playwright test
