name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Install backend dependencies
        run: yarn install --frozen-lockfile
        working-directory: apps/api

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: apps/web

      - name: Start backend and frontend servers
        run: |
          echo "Starting backend..."
          yarn --cwd apps/api dev > backend.log 2>&1 &

          echo "Starting frontend..."
          yarn --cwd apps/web dev > frontend.log 2>&1 &

          echo "Esperando os servidores..."

          # Espera até 60s pelos serviços
          npx wait-on http://localhost:3333 http://localhost:8080 --timeout 60000

          echo "Servidores iniciados"
        shell: bash

      - name: Show backend log
        run: cat backend.log || echo "backend.log não encontrado"

      - name: Show frontend log
        run: cat frontend.log || echo "frontend.log não encontrado"       

      - name: Run Playwright tests
        run: npx playwright test
